<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" height="200" width="600">

# Numpy Random Package Assignment

 The following assignment concerns the numpy.random package in Python. There are four tasks to be carried out in this Jupyter notebook.
1. Explain the overall purpose of the package. 
2. Explain the use of the “Simple random data” and “Permutations” functions. 
3. Explain the use and purpose of at least five “Distributions” functions. 
4. Explain the use of seeds in generating pseudorandom numbers.


## Purpose of the Numpy Random Package

NumPy is a Python extension module that provides efficient operation on arrays of homogeneous data. It allows python to serve as a high-level language for manipulating numerical data (4)

A NumPy array is a multidimensional array of objects all of the same type. In memory, it is an object which points to a block of memory, keeps track of the type of data stored in that memory, keeps track of how many dimensions there are and how large each one is, and - importantly - the spacing between elements along each axis. (4)

NumPy is a library for the Python programming language. NumPy enriches the programming language Python with powerful data structures, implementing multi-dimensional arrays and matrices. These data structures guarantee efficient calculations with matrices and arrays.(1. python-course)

The ancestor of NumPy, Numeric, was originally created by Jim Hugunin with contributions from several other developers. In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications. NumPy is open-source software and has many contributors.(wiki)

    

Numpy uses arrays!

## Advantages

NumPy has several advantages over using core Python mathemtatical functions, a few of which are outlined here:

1.NumPy is extremely fast when compared to core Python thanks to its heavy use of C extensions.

2.Many advanced Python libraries, such as Scikit-Learn, Scipy, and Keras, make extensive use of the NumPy library. Therefore, if you plan to pursue a career in data science or machine learning, NumPy is a very good tool to master.

3.NumPy comes with a variety of built-in functionalities, which in core Python would take a fair bit of custom code.(5)

## Introduction

We will begin my running a simple python example and then compare this to Numpy is more efficent quicker way to run datasets:

In [5]:
x = [2, 3, 4, 5, 6]
y = [a + 2 for a in x]
print(y)

[4, 5, 6, 7, 8]


Now lets simple numpy dataset but before we can use NumPy we will have to import it. It has to be imported like any other module:

In [6]:
import numpy 

Instead of using numpy we will use the shorthand np.

In [8]:
import numpy as np
x = np.array([2, 3, 4, 5, 6])
y = x + 2
print(y)

[4 5 6 7 8]


add a few simple examples

## Simple Random Data

In [14]:
np.random.randint(101, size=10)

array([100,  41,  13,  12,   0,  35,  57,   5,  52,  32])

This string generates random numbers betweem 0 and 100 with an array of 10 numbers.

In [17]:
np.random.randint(11, size=(2,4))

array([[10,  4,  9,  8],
       [ 9,  3,  4,  2]])

This string generates random numbers betweem 0 and 10 with 2 arrays of 4 numbers.

## Permuatations

In [22]:
x = np.arange(10)
np.random.shuffle(x)
x

array([4, 1, 6, 7, 3, 2, 9, 0, 8, 5])

This shuffle modifies a sequence in-place by shuffling its contents.

## Distributions

In [ ]:
gamma

In [ ]:
power

In [ ]:
uniform

In [ ]:
pareto

In [ ]:
logseries

## Seeds - Random Generator 

seed generator

1.  https://www.python-course.eu/numpy.php

2.  https://www.labri.fr/perso/nrougier/teaching/numpy/numpy.html

3.  https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

4.  https://www.scipy.org/scipylib/faq.html#what-is-numpy

5.  https://stackabuse.com/numpy-tutorial-a-simple-example-based-guide/#advantagesofnumpy 